checkpoint:
  path: models/finetuned_ITW/whisper_mesonet_20240616_070134/ckpt.pth
data:
  path: /home/jnb5885/in_the_wild
  seed: 42
  test_subset: subsets/ITW_marco.npy
model:
  id: whisper_mesonet
  name: whisper_mesonet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: true
    frontend_algorithm: []
    input_channels: 1
training:
  batch_size: 16
  max_epochs: 5
