_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
architecture:
    value: WAVE_WES
dataset:
    value: wild
epochs:
    value: 5
learning_rate_D:
    value: 0.00013333333333333334
learning_rate_G:
    value: 0.0004
penalty_amount:
    value: 8
