checkpoint:
  path: models/finetuned_ITW/mfcc_specrnet_20240615_172845/ckpt.pth
data:
  path: /home/jnb5885/in_the_wild
  seed: 42
  test_subset: subsets/ITW_marco.npy
model:
  id: mfcc_specrnet
  name: specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    frontend_algorithm:
    - mfcc
    input_channels: 1
training:
  batch_size: 16
  max_epochs: 5
