checkpoint:
  path: models/finetuned_ITW/whisper_mfcc_mesonet_20240616_083611/ckpt.pth
data:
  path: /home/jnb5885/in_the_wild
  seed: 42
  test_subset: subsets/ITW_marco.npy
model:
  id: whisper_mfcc_mesonet
  name: whisper_frontend_mesonet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: true
    frontend_algorithm:
    - mfcc
    input_channels: 2
training:
  batch_size: 16
  max_epochs: 5
